name: langtest_pro
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  animate_do: ^4.2.0
  audioplayers: ^6.4.0
  audio_waveforms: ^1.3.0
  glassmorphism: ^3.0.0
  percent_indicator: ^4.2.4
  lottie: ^3.3.1
  flip_card: ^0.7.0
  share_plus: ^10.1.4
  animated_notch_bottom_bar: ^1.0.3
  permission_handler: ^11.4.0
  image_picker: ^1.1.2
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.4
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  intl: ^0.20.2
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  hive: ^2.2.3
  firebase_core: ^3.13.1
  http: any
  hive_flutter: ^1.1.0
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.0
  fl_chart: ^0.71.0
  confetti: ^0.8.0
  simple_animations: ^5.1.0
  carousel_slider: ^5.0.0
  iconsax: ^0.0.8
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  flutter_svg: ^2.1.0
  flutter_staggered_animations: ^1.1.1
  supercharged: ^2.1.1
  animated_text_kit: ^4.2.3
  flutter_staggered_grid_view: ^0.7.0
  page_transition: ^2.2.1
  get: ^4.7.2
  dartz: ^0.10.1
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.2.1
  change_app_package_name: ^1.5.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/animations/confetti.json
    - assets/animations/success.json
    - assets/animations/try_again.json
    - assets/profile/avatar.png
    - assets/images/google_logo.png  