// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuGI4SxBlOsXembqOWquYEN0pUQsfnIeA',
    appId: '1:914970438031:web:0596372b5eef16d69043fa',
    messagingSenderId: '914970438031',
    projectId: 'lang-test-pro',
    authDomain: 'lang-test-pro.firebaseapp.com',
    storageBucket: 'lang-test-pro.firebasestorage.app',
    measurementId: 'G-C1D3R2EYEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUnZ3s9HTMM_8yZnasSc9aVFJ83O2Xh68',
    appId: '1:914970438031:android:6e35acaccab7967d9043fa',
    messagingSenderId: '914970438031',
    projectId: 'lang-test-pro',
    storageBucket: 'lang-test-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUWTWtomzwkb6zXqYqJQxZWoW8kM4GPJ0',
    appId: '1:914970438031:ios:9c45a535ee822e0a9043fa',
    messagingSenderId: '914970438031',
    projectId: 'lang-test-pro',
    storageBucket: 'lang-test-pro.firebasestorage.app',
    iosBundleId: 'com.nexaric.langtestpro.langtestPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUWTWtomzwkb6zXqYqJQxZWoW8kM4GPJ0',
    appId: '1:914970438031:ios:9c45a535ee822e0a9043fa',
    messagingSenderId: '914970438031',
    projectId: 'lang-test-pro',
    storageBucket: 'lang-test-pro.firebasestorage.app',
    iosBundleId: 'com.nexaric.langtestpro.langtestPro',
  );
}
